# Generated by Django 5.0.6 on 2024-07-01 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
